<div>
    <div data-bind="scope:'stopwatch'">
        <!-- ko template : getTemplate() -->
        <!-- /ko -->
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "stopwatch": {
                        "component": "Amasty_MaxModule/js/koStopwatch",
                        "template": "Amasty_MaxModule/koStopwatch"
                    }
                }
            }
        }
    }
</script>