<?php
    /**
     * @var \Amasty\MaxModule\Block\Form $block
     */
?>
<div>
    <form class="<?= $block->escapeHtml($block->getFormCss()); ?>">
        <input class="<?= $block->escapeHtml($block->getInputCss()); ?>" type="text" name="sku" placeholder="Enter  sku...">
        <?php if($block->isShowQtyField()): ?>
            <input class="<?= $block->escapeHtml($block->getInputCss()); ?>" type="number"
                   mame="qty" value="<?= $block->getQtyDefaultValue(); ?>" placeholder="Enter quantity...">
        <?php endif; ?>
        <?= $block->getChildHtml('Amasty_MaxModule.additional'); ?>
        <button class="<?= $block->escapeHtml($block->getBtnCss()); ?>" type="submit" disabled>
            <?= __('Send') ?>
        </button>
    </form>
</div>